sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: NhJT2fVT4accS02H5D51SqRarU5WSw25WDzk3/FbNOpYmg0i+NPjjxnbA6rAsgIelrhWwWZsJLg2OI5oaXPtRu7PBjVJ3qFnR6lghrHHuJN+7OkDFNF64QeFzGUUpSvEbGV/5Wn3n0nJMyaWB36K2iNMwd+ATKYA2SarhhCHLx7pDFFoAM7jKdPK1VhciB/mltC8TGRbNWQxQNnughwZuLw6N+eLD4DiDlrCyitbb76UbzhKVJP5hRLKQoTPjiPfWbQHFlXsJ/6XEAtA5AWvzxUedVefHc9RUZUrFHuHbhu1G0X4V8qne9DtosfxC/JRdz+GIj6simEPhiL1O62srKiBM/97x1kJKvSq2uiBRJTYKFHWYTgxoULLlOFxFycWPduspb1cJS4316MWD9GyQEULjMMhRwunN0DmxHZywKebndFurfw0V4922pV4I/XyKh53DxNTdTGMfUezb2W8UrL/uSWsxsFRy0STr5PA26uPkJCz57sNgHFAp4kPZhrTT0EIqoQm2aobAgjSgivsjKZXayVZyCK9sG63rGGX/GfCa895WYtqDR/HxaISzuvdhrxabJmPRKHy0Ipz2Umw6DrPQqXluyRFzV/Z2+n5B7L4cGAMpe9LoCw/zS8KHXL4s13EfzjgxQdiSzYqJ9RT3yDQvSR/M+gVuSFgRT3Kn+E=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: pJFBlFJiwaWfd3XngzCUUDZrTVEtHYRx+IKGk6MhbWqtbLBLQYh3b+XfBzZPR/f0LbxhAbH8RS8RGtCoGOy6lintJXPDMvvn875b7j4hQz+A6/fUuIOOQoSktlxpNR1I01qsaJUMLhYCr+8DfVQvkWSizSpTRac2WmYUzbUk0eSnHwea5OQYQJBwdsIfEL3996YCwT/b5XTI9YK1GAoYyB66amKzVVVUAGARk85axD6LnQmppCIGBNvBba1LJXTVkkwc7ofqneJjmq7sXjDl3TLLWJIMSkM20GQspcM/jtPXascs8dF0xbb0TqqPfuur9doz8QnYM914sIChBQJVFUq3wPjQmHlgikrsYpSN3ULy0qIzFw8h4kg5tHGdkZkIzvtsfcCLiB1zK5nT8wsdOaQZVV04vu5r9WeOFYeeTFz34H5VWcQPNgxmbI5JNEvtM/rbaA3cDfpxhmQ6FK428ThNoBhTQ5XGx89xr5BUaFbjI3kixLbfH2ttF7pw+bOiaaymKSwrRgio85aZmEkcwRwlVcp0wwM92WYFMEUoa7f0YyAhdGQsd+7kU3h8AUd4zSqrFCkZ/h7HgfgpwuP2qcgPu6ynEXxVeQocZP3CEzUSg4W1pEnkpWbtrPlwmRIUn2ACoanwcVMMgTOIW3Fi6nGzZy79uJhJ/iq9AoYC8Hw=
